// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://invqjjhpqohavcwzhrkq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImludnFqamhwcW9oYXZjd3pocmtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNDc3NjksImV4cCI6MjA2NDgyMzc2OX0.IECxyjT_awgNxNQM4fUO_a5f_Rq0zwUgXIzX87Yg5zQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);